Split into Builder & Final image
- Include some patches for 2.4.12 but it doesn't build yet due to another issue (HBASE-25983 probably)
- Remove unneeded packages

Note: The builder part is a bit torn to pieces due to debugging and needs to be cleaned up

diff --git a/hbase/Dockerfile b/hbase/Dockerfile
--- a/hbase/Dockerfile
+++ b/hbase/Dockerfile
@@ -1,39 +1,25 @@
 # syntax=docker/dockerfile:1
-FROM stackable/image/java-base
+FROM stackable/image/java-base AS builder
 
 ARG PRODUCT
 ARG PHOENIX
-ARG RELEASE
 ARG JMX_EXPORTER
 ARG HADOOP
-
-LABEL name="Apache HBase" \
-      maintainer="info@stackable.tech" \
-      vendor="Stackable GmbH" \
-      version="${PRODUCT}" \
-      release="${RELEASE}" \
-      summary="The Stackable image for Apache HBase." \
-      description="This image is deployed by the Stackable Operator for Apache HBase."
 
 # https://github.com/hadolint/hadolint/wiki/DL4006
 SHELL ["/bin/bash", "-o", "pipefail", "-c"]
 
+# zip required for the log4shell stuff
 RUN microdnf update && \
     microdnf install \
     git \
     gzip \
     java-11-openjdk-devel \
+    #java-1.8.0-openjdk-devel \
     maven \
-    python3 \
-    python3-pip  \
     tar \
     zip && \
     microdnf clean all
-
-RUN ln -s /usr/bin/python3 /usr/bin/python && \
-    ln -s /usr/bin/pip3 /usr/bin/pip
-
-ENV HOME=/stackable
 
 # The patch was generated by calling https://github.com/apache/hbase/pull/5233/commits/4f22587d02311b91c8371d5e6b9a2758d39ab26e.patch
 
@@ -44,10 +30,22 @@ USER stackable
 WORKDIR /stackable
 
 
-RUN curl --fail -L "https://repo.stackable.tech/repository/packages/hbase/hbase-${PRODUCT}-src.tar.gz" | tar -xzC . && \
-    mv hbase-${PRODUCT} hbase-${PRODUCT}-src && \
-    git apply --directory hbase-${PRODUCT}-src patches/HBASE-27860-4f22587d02311b91c8371d5e6b9a2758d39ab26e.patch && \
-    cd /stackable/hbase-${PRODUCT}-src/ && \
+#RUN curl --fail -L "https://repo.stackable.tech/repository/packages/hbase/hbase-${PRODUCT}-src.tar.gz" | tar -xzC . && \
+#    mv hbase-${PRODUCT} hbase-${PRODUCT}-src && \
+#    chmod +x patches/apply_patches.sh && \
+#    patches/apply_patches.sh ${PRODUCT} && \
+#    cd /stackable/hbase-${PRODUCT}-src/ && \
+#    mvn -Dhadoop.profile=3.0 -Dhadoop-three.version=${HADOOP} clean install -DskipTests && \
+#    mvn -Dhadoop.profile=3.0 -Dhadoop-three.version=${HADOOP} site -DskipTests && \
+#    mvn -Dhadoop.profile=3.0 -Dhadoop-three.version=${HADOOP} install assembly:single -DskipTests -Dcheckstyle.skip=true -Prelease && \
+#    tar -xzf hbase-assembly/target/hbase-${PRODUCT}-bin.tar.gz -C /stackable/ && \
+#    rm -rf /stackable/hbase-${PRODUCT}-src
+
+RUN curl --fail -L "https://repo.stackable.tech/repository/packages/hbase/hbase-${PRODUCT}-src.tar.gz" | tar -xzC .
+RUN mv hbase-${PRODUCT} hbase-${PRODUCT}-src
+RUN chmod +x patches/apply_patches.sh
+RUN patches/apply_patches.sh ${PRODUCT}
+RUN cd /stackable/hbase-${PRODUCT}-src/ && \
     mvn -Dhadoop.profile=3.0 -Dhadoop-three.version=${HADOOP} clean install -DskipTests && \
     mvn -Dhadoop.profile=3.0 -Dhadoop-three.version=${HADOOP} site -DskipTests && \
     mvn -Dhadoop.profile=3.0 -Dhadoop-three.version=${HADOOP} install assembly:single -DskipTests -Dcheckstyle.skip=true -Prelease && \
@@ -95,6 +93,38 @@ COPY shared/log4shell_1.6.1-log4shell_Linux_aarch64 /bin/log4shell_scanner_aarch
 COPY shared/log4shell_scanner /bin/log4shell_scanner
 RUN /bin/log4shell_scanner s /stackable/hbase-${PRODUCT}
 # ===
+
+
+# Final Image
+FROM stackable/image/java-base
+
+ARG PRODUCT
+ARG RELEASE
+
+LABEL name="Apache HBase" \
+      maintainer="info@stackable.tech" \
+      vendor="Stackable GmbH" \
+      version="${PRODUCT}" \
+      release="${RELEASE}" \
+      summary="The Stackable image for Apache HBase." \
+      description="This image is deployed by the Stackable Operator for Apache HBase."
+
+# https://github.com/hadolint/hadolint/wiki/DL4006
+SHELL ["/bin/bash", "-o", "pipefail", "-c"]
+
+# krb5-workstation for Kerberos support
+RUN microdnf update && \
+    microdnf install \
+    krb5-workstation && \
+    microdnf clean all && \
+    rm -rf /var/cache/yum
+
+COPY --chown=stackable:stackable --from=builder /stackable/hbase-${PRODUCT} /stackable/hbase-${PRODUCT}/
+COPY --chown=stackable:stackable --from=builder /stackable/jmx /stackable/jmx/
+RUN ln -s /stackable/hbase-${PRODUCT} /stackable/hbase
+
+ENV HOME=/stackable
+ENV PATH="${PATH}":/stackable/hbase/bin
 
 WORKDIR /stackable/hbase
 CMD ["./bin/hbase", "master", "start" ]
