Adding dropdown menu and component mapping to easily use this workflow

diff --git a/.github/workflows/mirror.yaml b/.github/workflows/mirror.yaml
--- a/.github/workflows/mirror.yaml
+++ b/.github/workflows/mirror.yaml
@@ -3,18 +3,22 @@
   on:
     workflow_dispatch:
       inputs:
-        src:
-          description: 'Location of the source image (example: registry.k8s.io/git-sync/git-sync:v3.6.4)'
+        #src:
+          #description: 'Location of the source image (example: registry.k8s.io/git-sync/git-sync:v3.6.4)'
+          #required: true
+        #dst:
+          #description: 'Name and tag of the destination image (example: git-sync:v3.6.4) ( nested structs are done with e.g. sig-storage/csi-provisioner:2.10.1 )'
+          #required: true
+        component:
+          type: choice
+          description: Components available using this workflow
+          options:
+          - "registry.k8s.io/git-sync/git-sync"
+          - "registry.k8s.io/sig-storage/csi-node-driver-registrar"
+          - "registry.k8s.io/sig-storage/csi-provisioner"
+        version:
+          description: 'Version of the component selected from the dropdown'
           required: true
-        dst:
-          description: 'Name and tag of the destination image (example: git-sync:v3.6.4) ( nested structs are done with e.g. sig-storage/csi-provisioner:2.10.1 )'
-          required: true
-        # name:
-          # type: choice
-          # description: Who to greet
-          # options: 
-          # - monalisa
-          # - cschleiden
 
   env:
     DST_REGISTRY_HARBOR: oci.stackable.tech
@@ -24,17 +28,13 @@
 
   jobs:
     mirror-image:
-      name: Pull, Retag and Push dependencies for ${{ github.event.inputs.dst }}
+      name: Pull, Retag and Push dependencies for ${{ github.event.inputs.component }}
       runs-on: ubuntu-latest
       strategy:
         matrix:
           architecture:
             - "amd64"
             - "arm64"
-          # get rid of inputs.src and just use matrix.src with defined images to pull ( maybe trigger them one by one if needed )
-          src:
-            - ""
-            - ""
       permissions:
         id-token: write
       outputs:
@@ -42,6 +42,7 @@
         REPO_DIGEST_OF_IMAGE_HARBOR_arm64: ${{ steps.push.outputs.REPO_DIGEST_OF_IMAGE_HARBOR_arm64 }}
         REPO_DIGEST_OF_IMAGE_NEXUS_amd64: ${{ steps.push.outputs.REPO_DIGEST_OF_IMAGE_NEXUS_amd64 }}
         REPO_DIGEST_OF_IMAGE_NEXUS_arm64: ${{ steps.push.outputs.REPO_DIGEST_OF_IMAGE_NEXUS_arm64 }}
+        PRODUCT: ${{ steps.map.outputs.PRODUCT }}
       steps:
         - name: Login to Stackable Harbor
           uses: docker/login-action@0d4c9c5ea7693da7b068278f7b52bda2a190a446 # v3.2.0
@@ -56,28 +57,41 @@
             username: github
             password: ${{ secrets.NEXUS_PASSWORD }}
         - name: Pull image from source registry
-          run: docker pull "${{ github.event.inputs.src }}" --platform ${{ matrix.architecture }}
+          run: docker pull "${{ github.event.inputs.component }}" --platform ${{ matrix.architecture }}
+        - name: Map components onto component names
+          id: map
+          run: |
+            if [ ${{ github.event.inputs.component }} == "registry.k8s.io/git-sync/git-sync"]; then
+              echo "PRODUCT="git-sync"" >> "$GITHUB_OUTPUT"
+            elif [ ${{ github.event.inputs.component }} == "registry.k8s.io/sig-storage/csi-node-driver-registrar" ]; then
+              echo "PRODUCT="sig-storage/csi-node-driver-registrar"" >> "$GITHUB_OUTPUT"
+            elif [ ${{ github.event.inputs.component }} == "registry.k8s.io/sig-storage/csi-provisioner" ]; then
+              echo "PRODUCT="sig-storage/csi-provisioner"" >> "$GITHUB_OUTPUT"
+            else
+              echo "Product not recognized"
+              exit 1
+            fi
         - name: Retag image
           run: |
             # Tagging the same image two times to push to Nexus and Harbor
-            docker tag "${{ github.event.inputs.src }}" "$DST_REGISTRY_HARBOR/${{ env.DST_PROJECT_HARBOR }}/${{ github.event.inputs.dst }}-${{ matrix.architecture }}"
-            docker tag "${{ github.event.inputs.src }}" "$DST_REGISTRY_NEXUS/$DST_PROJECT_NEXUS/${{ github.event.inputs.dst }}-${{ matrix.architecture }}"
+            docker tag "${{ github.event.inputs.component }}" "$DST_REGISTRY_HARBOR/${{ env.DST_PROJECT_HARBOR }}/${{ steps.map.outputs.PRODUCT }}-${{ matrix.architecture }}"
+            docker tag "${{ github.event.inputs.component }}" "$DST_REGISTRY_NEXUS/$DST_PROJECT_NEXUS/${{ steps.map.outputs.PRODUCT }}-${{ matrix.architecture }}"
         - uses: sigstore/cosign-installer@59acb6260d9c0ba8f4a2f9d9b48431a222b68e20 # v3.5.0
         - name: Push image to destination registry
           id: push
           run: |
-            DOCKER_OUTPUT_HARBOR="$(docker push "$DST_REGISTRY_HARBOR/${{ env.DST_PROJECT_HARBOR }}/${{ github.event.inputs.dst }}-${{ matrix.architecture }}")";
-            DOCKER_OUTPUT_NEXUS="$(docker push "$DST_REGISTRY_NEXUS/$DST_PROJECT_NEXUS/${{ github.event.inputs.dst }}-${{ matrix.architecture }}")";
+            DOCKER_OUTPUT_HARBOR="$(docker push "$DST_REGISTRY_HARBOR/${{ env.DST_PROJECT_HARBOR }}/${{ steps.map.outputs.PRODUCT }}:${{ github.event.inputs.version }}-${{ matrix.architecture }}")";
+            DOCKER_OUTPUT_NEXUS="$(docker push "$DST_REGISTRY_NEXUS/$DST_PROJECT_NEXUS/${{ steps.map.outputs.PRODUCT }}:${{ github.event.inputs.version }}-${{ matrix.architecture }}")";
             # Obtain the digest of the pushed image from the output of `docker push`, because signing by tag is deprecated and will be removed from cosign in the future
             REPO_DIGEST_OF_IMAGE_HARBOR="$(echo "$DOCKER_OUTPUT_HARBOR" | awk '/^\S+: digest: sha256:[0-9a-f]{64} size: [0-9]+$/ { print $3 }')";
             REPO_DIGEST_OF_IMAGE_NEXUS="$(echo "$DOCKER_OUTPUT_NEXUS" | awk '/^\S+: digest: sha256:[0-9a-f]{64} size: [0-9]+$/ { print $3 }')";
             # Check both architectures to see if both are available
             if [ -z "$REPO_DIGEST_OF_IMAGE_HARBOR" ]; then
-              echo "Could not find repo digest for container image: $DST_REGISTRY_HARBOR/${{ env.DST_PROJECT_HARBOR }}/${{ github.event.inputs.dst }}-${{ matrix.architecture }}"
+              echo "Could not find repo digest for container image: $DST_REGISTRY_HARBOR/${{ env.DST_PROJECT_HARBOR }}/${{ steps.map.outputs.PRODUCT }}:${{ github.event.inputs.version }}-${{ matrix.architecture }}"
               exit 1
             fi
             if [ -z "$REPO_DIGEST_OF_IMAGE_NEXUS" ]; then
-              echo "Could not find repo digest for container image: $DST_REGISTRY_NEXUS/$DST_PROJECT_NEXUS/${{ github.event.inputs.dst }}-${{ matrix.architecture }}"
+              echo "Could not find repo digest for container image: $DST_REGISTRY_NEXUS/$DST_PROJECT_NEXUS/${{ steps.map.outputs.PRODUCT }}:${{ github.event.inputs.version }}-${{ matrix.architecture }}"
               exit 1
             fi
             # Generating output variables for later manifest list creation
@@ -90,9 +104,9 @@
             fi
             # This generates a signature and publishes it to the registry, next to the image
             # Uses the keyless signing flow with Github Actions as identity provider
-            cosign sign -y "$DST_REGISTRY_HARBOR/${{ env.DST_PROJECT_HARBOR }}/${{ github.event.inputs.dst }}-${{ matrix.architecture }}@$REPO_DIGEST_OF_IMAGE_HARBOR"
+            cosign sign -y "$DST_REGISTRY_HARBOR/${{ env.DST_PROJECT_HARBOR }}/${{ steps.map.outputs.PRODUCT }}:${{ github.event.inputs.version }}-${{ matrix.architecture }}@$REPO_DIGEST_OF_IMAGE_HARBOR"
     publish_manifest:
-      name: Build/Publish ${{ github.event.inputs.dst }} Manifests
+      name: Build/Publish ${{ github.event.inputs.component }} Manifests
       runs-on: ubuntu-latest
       needs: mirror-image
       permissions:
@@ -100,24 +114,24 @@
       steps:
         - name: Checkout Repository
           uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
-        - name: Split version and product
-          id: split
-          run: | # Cut neccessary since this action inputs and binary destinations are different to products and operators 
-            echo "PRDOUCT_NAME="$(cut -d':' -f1 <<<< '${{ github.event.inputs.dst }}')"" >> "$GITHUB_OUTPUT"
-            echo "PRODUCT_VERSION="$(cut -d':' -f2 <<<< '${{ github.event.inputs.dst }}')"" >> "$GITHUB_OUTPUT"
+        #- name: Split version and product
+          #id: split
+          #run: | # Cut neccessary since this action inputs and binary destinations are different to products and operators
+            #echo "PRDOUCT_NAME="$(cut -d':' -f1 <<<< '${{ github.event.inputs.dst }}')"" >> "$GITHUB_OUTPUT"
+            #echo "PRODUCT_VERSION="$(cut -d':' -f2 <<<< '${{ github.event.inputs.dst }}')"" >> "$GITHUB_OUTPUT"
         - name: Build Product Manifest List ( Nexus )
           uses: ./.github/actions/publish-manifest
           with:
-            product: ${{ steps.split.outputs.PRDOUCT_NAME }}
+            product: ${{ needs.mirror-image.outputs.PRODUCT }}
             registry: $DST_REGISTRY_NEXUS/$DST_PROJECT_NEXUS
-            image-version: ${{ steps.split.outputs.PRDOUCT_VERSION }}
+            image-version: ${{ github.event.inputs.version }}
             nexus-password: ${{ secrets.NEXUS_PASSWORD }}
             harbor-secret: ${{ secrets.HARBOR_ROBOT_SDP_GITHUB_ACTION_BUILD_SECRET }}
         - name: Build Product Manifest List ( Harbor )
           uses: ./.github/actions/publish-manifest
           with:
-            product: ${{ steps.split.outputs.PRDOUCT_NAME }}
-            image-version: ${{ steps.split.outputs.PRDOUCT_VERSION }}
+            product: ${{ needs.mirror-image.outputs.PRODUCT }}
+            image-version: ${{ github.event.inputs.version }}
             registry: $DST_REGISTRY_HARBOR/$DST_PROJECT_HARBOR
             nexus-password: ${{ secrets.NEXUS_PASSWORD }}
             harbor-secret: ${{ secrets.HARBOR_ROBOT_SDP_GITHUB_ACTION_BUILD_SECRET }}
