Fix release workflow (#789)
* Fix release workflow

- The enumerate-product-versions.py would not work because it can't find the module "conf" since it was moved to the .scripts subfolder

- Changes the release workflow to fail when the enumerate script fails. It used to just swallow the error

* Silence yamllint

* Add notes

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -97,10 +97,10 @@ jobs:
           # Bake images and load them to local docker repo for signing
           # TODO: buildx cannot --load and --push at the same time
           # Tagging images with the architecture they were build on
-          ARCH_FOR_DOCKER="$(arch | sed -e 's#x86_64#amd64#' | sed -e 's#aarch64#arm64#')"
+          ARCH="$(uname -m | sed -e 's#x86_64#amd64#' | sed -e 's#aarch64#arm64#')"
           bake --product "${{ matrix.product }}" \
-          --image-version "${GITHUB_REF_NAME}-${ARCH_FOR_DOCKER}" \
-          --architecture "linux/${ARCH_FOR_DOCKER}" \
+          --image-version "${GITHUB_REF_NAME}-${ARCH}" \
+          --architecture "linux/${ARCH}" \
           --organization stackable \
           --shard-count "${{matrix.shard_count}}" \
           --shard-index "${{matrix.shard_index}}" \
@@ -187,7 +187,12 @@ jobs:
           DOCKER_USER: github
           DOCKER_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
         run: |
-          for product_and_version in $(python3 .scripts/enumerate-product-versions.py); do
+          if ! product_and_versions=$(python3 .scripts/enumerate-product-versions.py); then
+            echo "Python script failed"
+            exit 1
+          fi
+
+          for product_and_version in $product_and_versions; do
             PRODUCT="$(echo "$product_and_version" | cut -d '#' -f 1)"
             VERSION="$(echo "$product_and_version" | cut -d '#' -f 2)"
 
